[core] operator== hook
SanderMertens/flecs pull request #1455
Opened 2024-11-29 13:45 UTC by jpeletier

Note, requires #1454 to be merged first.

Building on the previous PR, this one adds a hook for `operator==`. It will detect this operator in a component definition and bind a hook to it that can be used to test components for equality.

If this operator is not defined but the compare operator is, Flecs will automatically derive this operator.

```cpp
    class Vec2D {
    public:
        float x, y;
    
        Vec2D(float x = 0.0f, float y = 0.0f) : x(x), y(y) {}
    
        // Function to calculate the modulus (magnitude) of the vector
        float modulus() const {
            return std::sqrt(x * x + y * y);
        }
    
        // Overload operator< to compare vectors based on their modulus
        bool operator<(const Vec2D& other) const {
            return this->modulus() < other.modulus();
        }
    
        // Overload operator== to compare vectors with a precision tolerance of 0.001
        bool operator==(const Vec2D& other) const {
            return std::fabs(this->x - other.x) < 0.001 && std::fabs(this->y - other.y) < 0.001;
        }
    };

    flecs::world ecs;

    auto vtype =
        ecs.component<Vec2D>();  // will automatically register the above hooks.

    Vec2D a(1, 2);
    Vec2D b(2, 3);
    Vec2D c(1.00001, 1.9999999);

    const ecs_type_info_t *ti = ecs_get_type_info(ecs, vtype);

    assert(ti->hooks.equals(&a, &b, ti) == false); // ok!
    assert(ti->hooks.equals(&a, &c, ti) == true);  // ok!
    assert(ti->hooks.cmp(&b, &a, ti) > 0);         // ok!

```

2025-01-07 22:43 UTC, SanderMertens requested changes

2025-01-08 15:27 UTC, jpeletier commented on include/flecs/addons/cpp/component.hpp
> +        flecs::type_hooks_t h = this->get_hooks();
Fixed

2025-01-08 15:28 UTC, jpeletier commented on include/flecs/addons/cpp/component.hpp
> +    component<T>& op_compare() {
Fixed

2025-01-08 15:28 UTC, jpeletier commented on src/addons/meta/rtt_lifecycle.c
> +        ctor_hook_required ? flecs_rtt_struct_ctor : NULL,
Fixed.
This change made sense in some internal refactor. Not anymore.

2025-01-08 15:37 UTC, jpeletier commented on src/addons/meta/rtt_lifecycle.c
> +    hooks.ctor = ctor_hook_required && !(flags & ECS_TYPE_HOOK_CTOR_ILLEGAL) ?
This is due to the new flags checks in `ecs_set_hooks_id()`. It now requires that hooks are set to `NULL` if they are to be illegal: The PR enables the commented-out asserts in there:
```cpp
/* TODO: enable asserts once RTT API is updated */
```
... and also unquarantines several tests in `ComponentLifecycle.c`.

2025-01-08 16:12 UTC, jpeletier commented on src/addons/meta/rtt_lifecycle.c
> +        hooks.lifecycle_ctx_free = flecs_rtt_free_lifecycle_nop;
The existing approach didn't actually work as intended. Specifically, `ecs_set_hooks_id` [does not allow you to unset](https://github.com/SanderMertens/flecs/blob/8a1e9abe412eda7cd7f2a7440dac7499ce42cdca/src/world.c#L1336) `lifecycle_ctx_free` once it's been set.

This issue went unnoticed in other cases (e.g., for `ctor`, `dtor`, etc.) because if any field in a struct required a runtime-generated hook, the struct would always continue requiring hooks as new fields were added. In those cases, the lifecycle context wouldn't need to be removed.

However, handling `cmp` and `equals` hooks is different. Initially, a struct might be comparable because its first field is comparable, and so an autogenerated compare hook is added. But if a later field is not comparable, the entire struct becomes uncomparable, even if further comparable fields are added later. This means the lifecycle context must be removed, unless the struct coincidentally still requires other hooks (e.g., `ctor` or `dtor`).

Since `ecs_set_hooks_id` doesn't support unsetting `lifecycle_ctx_free`, I opted to replace it with a no-op function. 

I could change `ecs_set_hooks_id` to do what I want and avoid the nop, but that would break a pattern in there, so it is better to have this conversation and decide.

So that's why 😉

2025-01-08 16:13 UTC, jpeletier commented on src/addons/meta/rtt_lifecycle.c
> +    if (hooks.ctor || hooks.dtor || hooks.move ||
Same as above, due to the refactor required to comply with `ecs_set_hooks_id()` strict flags check.

2025-01-08 16:19 UTC, jpeletier commented on src/world.c
> +        ti->hooks.move_dtor = flecs_move_ctor_illegal;
This is unrelated to this PR, I just spotted this bug and fixed it along the way before I forgot: The wrong hook was being set to the `flecs_move_ctor_illegal` illegal handler.

2025-03-11 17:56 UTC, SanderMertens commented on src/addons/meta/rtt_lifecycle.c
> +        hooks.lifecycle_ctx_free = flecs_rtt_free_lifecycle_nop;
This sounds pretty hacky but OK for now.

2025-03-11 17:59 UTC, SanderMertens commented on src/addons/meta/rtt_lifecycle.c
> +        if(ecs_id_in_use(w, component) ||
This doesn't seem like a correct check. This code should be executed at a time where it's guaranteed that a component is not yet in use. OK for now but should probably be improved later.

2025-03-11 18:03 UTC, SanderMertens commented on test/meta/src/RuntimeTypes.c
> +    const NestedStructWithStrings *ptr2 =
Not going to fail the PR on this, but the `{ }` where there so you don't have to give the variables different names, which makes code easier to extend/copy paste. For future ref please don't remove `{ }`

2025-03-11 18:05 UTC, SanderMertens commented
LGTM!

2025-03-11 18:05 UTC, merged