Changed all floats to doubles to get around floating point rounding e…
SanderMertens/flecs pull request #265
Opened 2020-11-05 19:41 UTC by markgerl-NG

…rrors when running multiple systems at different FPS rates.

2020-11-08 20:31 UTC, SanderMertens requested changes

2020-11-08 20:31 UTC, SanderMertens commented on src/map.c
> -    return next_pow_of_2((int32_t)((float)element_count * LOAD_FACTOR));
This is not used for FPS calculation, doesn't need to change.

2020-11-08 20:31 UTC, SanderMertens commented on src/modules/pipeline/worker.c
> +        world->stats.system_time_total += (double)ecs_time_measure(&start);
The return type of `ecs_time_measure` is already a double, cast is not necessary.

2020-11-08 20:31 UTC, SanderMertens commented on src/world.c
> +        world->stats.merge_time_total += (double)ecs_time_measure(&t_start);
Cast is not necessary, return type is already a double.

2020-11-08 20:31 UTC, SanderMertens commented on src/world.c
> +        world->stats.frame_time_total += (double)ecs_time_measure(&t);
Cast not necessary, return type is already a double.

2020-11-09 14:24 UTC, markgerl-NG reviewed
All seem reasonable - I've made the changes. But, I may be reading this PR wrong - you may have already made the changes. #confusing

2020-11-18 18:49 UTC, SanderMertens commented
A quick test with doubles shows that this doesn't solve the issue. This is the output for a timer that increases with intervals of 0.1, and has a timeout at 1.0:
```c
time_elapsed = 0.1000000000000000055511, timeout = 1.0000000000000000000000
time_elapsed = 0.2000000000000000111022, timeout = 1.0000000000000000000000
time_elapsed = 0.3000000000000000444089, timeout = 1.0000000000000000000000
time_elapsed = 0.4000000000000000222045, timeout = 1.0000000000000000000000
time_elapsed = 0.5000000000000000000000, timeout = 1.0000000000000000000000
time_elapsed = 0.5999999999999999777955, timeout = 1.0000000000000000000000
time_elapsed = 0.6999999999999999555911, timeout = 1.0000000000000000000000
time_elapsed = 0.7999999999999999333866, timeout = 1.0000000000000000000000
time_elapsed = 0.8999999999999999111822, timeout = 1.0000000000000000000000
time_elapsed = 0.9999999999999998889777, timeout = 1.0000000000000000000000
time_elapsed = 1.0999999999999998667732, timeout = 1.0000000000000000000000
triggered! (1.100000)
```
The system triggers at the 11th frame as the result of a floating point not having integer accuracy. This can only be addressed by using integer timeout values.

2020-11-18 18:49 UTC, closed without merging